import heroImg from '../assets/images/hero_gallery_sculpture_1790836421246.jpg';
import prismImg from '../assets/images/art_chromatic_prism_1790836434332.jpg';
import geoImg from '../assets/images/art_minimalist_geometry_1790836450274.jpg';
import floraImg from '../assets/images/art_botanical_porcelain_1790836465523.jpg';
import archesImg from '../assets/images/art_surreal_arches_1790836476885.jpg';

import { Artwork, ArtistProfile, User, Order } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user_admin_01',
    name: 'Artnova Curator (Admin)',
    email: 'admin@artnova.gallery',
    role: 'admin',
    createdAt: '2026-01-10T09:00:00Z',
    profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
  },
  {
    id: 'user_artist_01',
    name: 'Elena Rostova',
    email: 'elena@rostova-art.com',
    role: 'artist',
    status: 'approved',
    createdAt: '2026-01-15T10:30:00Z',
    profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=250&q=80',
  },
  {
    id: 'user_artist_02',
    name: 'Kai Takahashi',
    email: 'kai@takahashi-digital.jp',
    role: 'artist',
    status: 'approved',
    createdAt: '2026-02-01T14:15:00Z',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
  },
  {
    id: 'user_artist_03',
    name: 'Maya Lin Sorenson',
    email: 'maya@sorenson-art.studio',
    role: 'artist',
    status: 'approved',
    createdAt: '2026-02-14T11:45:00Z',
    profileImage: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=250&q=80',
  },
  {
    id: 'user_artist_04',
    name: 'Marcus Vance',
    email: 'marcus@vancedesign.art',
    role: 'artist',
    status: 'approved',
    createdAt: '2026-03-01T16:00:00Z',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
  },
  {
    id: 'user_artist_pending',
    name: 'Julian Reed',
    email: 'julian@prismastudio.io',
    role: 'artist',
    status: 'pending',
    createdAt: '2026-03-24T18:20:00Z',
    profileImage: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=250&q=80',
  },
  {
    id: 'user_buyer_01',
    name: 'Aria Sterling',
    email: 'buyer@collector.org',
    role: 'buyer',
    createdAt: '2026-02-18T13:20:00Z',
    profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=250&q=80',
  },
];

export const INITIAL_ARTISTS: ArtistProfile[] = [
  {
    id: 'artist_01',
    userId: 'user_artist_01',
    artistName: 'Elena Rostova',
    email: 'elena@rostova-art.com',
    bio: 'Pioneering surreal architectural landscapes and spatial light studies. Exhibited at Milan Digital Biennial and Tokyo Museum of Future Art.',
    location: 'Vienna, Austria',
    website: 'https://rostova-art.com',
    socialTwitter: '@elena_rostova',
    socialInstagram: '@rostova_digital',
    profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=250&q=80',
    coverImage: heroImg,
    status: 'approved',
    createdAt: '2026-01-15T10:30:00Z',
    approvedAt: '2026-01-16T12:00:00Z',
    totalArtworks: 2,
    totalSales: 34,
    totalEarnings: 14250,
  },
  {
    id: 'artist_02',
    userId: 'user_artist_02',
    artistName: 'Kai Takahashi',
    email: 'kai@takahashi-digital.jp',
    bio: 'Fluid chromatic prism studies, light refraction, and pure perceptual color fields in ultra-high resolution.',
    location: 'Kyoto, Japan',
    website: 'https://takahashi-digital.jp',
    socialTwitter: '@kai_takahashi',
    socialInstagram: '@takahashi_art',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    coverImage: prismImg,
    status: 'approved',
    createdAt: '2026-02-01T14:15:00Z',
    approvedAt: '2026-02-02T09:00:00Z',
    totalArtworks: 1,
    totalSales: 41,
    totalEarnings: 14350,
  },
  {
    id: 'artist_03',
    userId: 'user_artist_03',
    artistName: 'Maya Lin Sorenson',
    email: 'maya@sorenson-art.studio',
    bio: 'Porcelain botanicals and organic computational sculptures exploring translucence and sacred geometry.',
    location: 'Stockholm, Sweden',
    website: 'https://sorenson-art.studio',
    socialTwitter: '@maya_sorenson',
    socialInstagram: '@sorenson_sculpt',
    profileImage: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=250&q=80',
    coverImage: floraImg,
    status: 'approved',
    createdAt: '2026-02-14T11:45:00Z',
    approvedAt: '2026-02-15T15:20:00Z',
    totalArtworks: 1,
    totalSales: 19,
    totalEarnings: 7980,
  },
  {
    id: 'artist_04',
    userId: 'user_artist_04',
    artistName: 'Marcus Vance',
    email: 'marcus@vancedesign.art',
    bio: 'Minimalist constructivist compositions balancing mineral sandstones, architectural tension, and pure ochre pigment.',
    location: 'London, UK',
    website: 'https://vancedesign.art',
    socialTwitter: '@marcus_vance',
    socialInstagram: '@vance_minimal',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    coverImage: geoImg,
    status: 'approved',
    createdAt: '2026-03-01T16:00:00Z',
    approvedAt: '2026-03-02T10:45:00Z',
    totalArtworks: 1,
    totalSales: 28,
    totalEarnings: 5460,
  },
  {
    id: 'artist_pending_01',
    userId: 'user_artist_pending',
    artistName: 'Julian Reed',
    email: 'julian@prismastudio.io',
    bio: 'Algorithmic generative color fields and recursive spatial tessellations exploring mathematical harmony.',
    location: 'Toronto, Canada',
    website: 'https://prismastudio.io',
    socialTwitter: '@reed_prisma',
    profileImage: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=250&q=80',
    status: 'pending',
    createdAt: '2026-03-24T18:20:00Z',
    totalArtworks: 0,
    totalSales: 0,
    totalEarnings: 0,
  },
];

export const INITIAL_ARTWORKS: Artwork[] = [
  {
    id: 'art_001',
    artistId: 'artist_01',
    artistName: 'Elena Rostova',
    artistEmail: 'elena@rostova-art.com',
    title: 'Luminous Sanctuary No. 1',
    description: 'An architectural fine art meditation on light, purity, and sculptural geometry in a serene museum space. Volumetric morning sunlight illuminates clean limestone textures.',
    previewImage: heroImg,
    digitalFile: {
      fileName: 'Luminous_Sanctuary_Master_8K.zip',
      fileSizeBytes: 78500000,
      fileFormat: 'TIFF (16-bit) + Ultra-Res RAW + Color Profile',
      resolution: '8192 × 4608 px (8K DCI)',
      colorSpace: 'Display P3 / Adobe RGB',
      dpi: 300,
      downloadToken: 'artnova_token_sanctuary_89417f',
    },
    price: 320,
    currency: 'USD',
    category: 'Architecture',
    tags: ['Architecture', 'Sculpture', 'Gallery', 'Minimalism', 'Light'],
    copyright: '© Elena Rostova. All rights reserved.',
    createdAt: '2026-01-20T14:30:00Z',
    updatedAt: '2026-01-20T14:30:00Z',
    status: 'published',
    salesCount: 22,
    viewCount: 1480,
    featured: true,
  },
  {
    id: 'art_002',
    artistId: 'artist_02',
    artistName: 'Kai Takahashi',
    artistEmail: 'kai@takahashi-digital.jp',
    title: 'Chromatic Dispersion & Glass Wave',
    description: 'A study of light bending through high-refraction optical prisms on museum white paper. Nuanced iridescence and subtle prismatic ribbons create serene vibrational energy.',
    previewImage: prismImg,
    digitalFile: {
      fileName: 'Chromatic_Dispersion_Master_Archive.zip',
      fileSizeBytes: 64200000,
      fileFormat: 'TIFF (16-bit) + PNG + Print-Ready PDF',
      resolution: '6400 × 4800 px',
      colorSpace: 'Adobe RGB 1998',
      dpi: 300,
      downloadToken: 'artnova_token_chromatic_3312b',
    },
    price: 290,
    currency: 'USD',
    category: 'Abstract',
    tags: ['Chromatic', 'Prism', 'Refraction', 'Fluid', 'Light'],
    copyright: '© Kai Takahashi. All rights reserved.',
    createdAt: '2026-02-04T10:10:00Z',
    updatedAt: '2026-02-04T10:10:00Z',
    status: 'published',
    salesCount: 41,
    viewCount: 2840,
    featured: true,
  },
  {
    id: 'art_003',
    artistId: 'artist_03',
    artistName: 'Maya Lin Sorenson',
    artistEmail: 'maya@sorenson-art.studio',
    title: 'Porcelain Flora & Gold Leaf',
    description: 'Transcendent porcelain botanical sculpture with translucent crystalline petals and delicate 24-karat gold leaf accents. Captured with studio rim illumination on clean linen backdrop.',
    previewImage: floraImg,
    digitalFile: {
      fileName: 'Porcelain_Flora_Master_Archive.zip',
      fileSizeBytes: 92400000,
      fileFormat: 'TIFF (16-bit uncompressed) + Multi-pass Layers',
      resolution: '6400 × 4800 px',
      colorSpace: 'Display P3',
      dpi: 300,
      downloadToken: 'artnova_token_porcelainflora_8819c',
    },
    price: 450,
    currency: 'USD',
    category: '3D & Botanical',
    tags: ['Botanical', 'Porcelain', 'Gold Leaf', 'Sculpture', 'Ethereal'],
    copyright: '© Maya Lin Sorenson. All rights reserved.',
    createdAt: '2026-02-18T16:45:00Z',
    updatedAt: '2026-02-18T16:45:00Z',
    status: 'published',
    salesCount: 19,
    viewCount: 1920,
    featured: true,
  },
  {
    id: 'art_004',
    artistId: 'artist_04',
    artistName: 'Marcus Vance',
    artistEmail: 'marcus@vancedesign.art',
    title: 'Bauhaus Spatial Balance IV',
    description: 'Balanced mineral sandstones, charcoal geometric planes, and warm ochre tones in harmonious architectural tension. Inspired by mid-century modernism and tectonic balance.',
    previewImage: geoImg,
    digitalFile: {
      fileName: 'Bauhaus_Spatial_Balance_Master.zip',
      fileSizeBytes: 54100000,
      fileFormat: 'TIFF (16-bit) + Vector EPS + Master Print PDF',
      resolution: '6400 × 4800 px',
      colorSpace: 'sRGB / Adobe RGB',
      dpi: 300,
      downloadToken: 'artnova_token_bauhaus_7721a',
    },
    price: 240,
    currency: 'USD',
    category: 'Minimalism',
    tags: ['Minimalism', 'Abstract', 'Geometric', 'Modernist', 'Bauhaus'],
    copyright: '© Marcus Vance. All rights reserved.',
    createdAt: '2026-03-05T09:30:00Z',
    updatedAt: '2026-03-05T09:30:00Z',
    status: 'published',
    salesCount: 28,
    viewCount: 1650,
    featured: true,
  },
  {
    id: 'art_005',
    artistId: 'artist_01',
    artistName: 'Elena Rostova',
    artistEmail: 'elena@rostova-art.com',
    title: 'Portals to Azure Silence',
    description: 'Monumental white architectural arches overlooking still azure waters under soft morning daylight. An evocative meditation on stillness, space, and eternal geometry.',
    previewImage: archesImg,
    digitalFile: {
      fileName: 'Portals_to_Azure_Silence_Master.zip',
      fileSizeBytes: 86300000,
      fileFormat: 'TIFF (16-bit) + High-Dynamic Range EXR',
      resolution: '6400 × 4800 px',
      colorSpace: 'ProPhoto RGB',
      dpi: 300,
      downloadToken: 'artnova_token_azureportals_9941x',
    },
    price: 380,
    currency: 'USD',
    category: 'Surrealism',
    tags: ['Surrealism', 'Arches', 'Water', 'Silence', 'Architectural'],
    copyright: '© Elena Rostova. All rights reserved.',
    createdAt: '2026-03-12T11:20:00Z',
    updatedAt: '2026-03-12T11:20:00Z',
    status: 'published',
    salesCount: 12,
    viewCount: 2100,
    featured: true,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-8491-X',
    buyerId: 'user_buyer_01',
    buyerName: 'Aria Sterling',
    buyerEmail: 'buyer@collector.org',
    items: [
      {
        artworkId: 'art_002',
        title: 'Chromatic Dispersion & Glass Wave',
        artistId: 'artist_02',
        artistName: 'Kai Takahashi',
        artistEmail: 'kai@takahashi-digital.jp',
        price: 290,
        previewImage: prismImg,
        digitalFile: INITIAL_ARTWORKS[1].digitalFile,
      },
    ],
    totalAmount: 290,
    currency: 'USD',
    paymentStatus: 'paid',
    paymentMethod: 'Digital Payment / Credit Card',
    createdAt: '2026-03-25T14:40:00Z',
    downloadStatus: 'available',
  },
  {
    id: 'ORD-8219-B',
    buyerId: 'user_buyer_01',
    buyerName: 'Aria Sterling',
    buyerEmail: 'buyer@collector.org',
    items: [
      {
        artworkId: 'art_001',
        title: 'Luminous Sanctuary No. 1',
        artistId: 'artist_01',
        artistName: 'Elena Rostova',
        artistEmail: 'elena@rostova-art.com',
        price: 320,
        previewImage: heroImg,
        digitalFile: INITIAL_ARTWORKS[0].digitalFile,
      },
    ],
    totalAmount: 320,
    currency: 'USD',
    paymentStatus: 'paid',
    paymentMethod: 'Digital Payment / Credit Card',
    createdAt: '2026-03-20T19:15:00Z',
    downloadStatus: 'downloaded',
  },
];

export const CATEGORIES = [
  'All',
  'Architecture',
  'Abstract',
  '3D & Botanical',
  'Minimalism',
  'Surrealism',
  'Generative',
];
